package io.github.finalparadox.item;
import com.google.common.collect.*;import net.minecraft.network.chat.Component;import net.minecraft.world.entity.*;import net.minecraft.world.entity.ai.attributes.*;import net.minecraft.world.item.*;import net.minecraft.world.item.enchantment.Enchantments;import net.minecraft.world.level.Level;import java.util.*;
public final class VoidArmorItem extends ArmorItem{
 public static final String KILLS_KEY="finalparadox.void_armor_kills";private final Multimap<Attribute,AttributeModifier>mods;
 public VoidArmorItem(){super(VoidArmorMaterial.INSTANCE,Type.CHESTPLATE,new Properties().stacksTo(1).fireResistant());ImmutableMultimap.Builder<Attribute,AttributeModifier>b=ImmutableMultimap.builder();b.putAll(super.getDefaultAttributeModifiers(EquipmentSlot.CHEST));b.put(Attributes.MAX_HEALTH,new AttributeModifier(UUID.fromString("b4594d87-9ba2-4f7e-beb1-bfce37c0e182"),"Void armor health",4,AttributeModifier.Operation.ADDITION));b.put(Attributes.ATTACK_DAMAGE,new AttributeModifier(UUID.fromString("354029b4-ef33-4d8e-8328-25a785b03157"),"Void armor damage",.05,AttributeModifier.Operation.MULTIPLY_BASE));mods=b.build();}
 @Override public Multimap<Attribute,AttributeModifier>getDefaultAttributeModifiers(EquipmentSlot slot){return slot==EquipmentSlot.CHEST?mods:super.getDefaultAttributeModifiers(slot);}
 @Override public ItemStack getDefaultInstance(){ItemStack s=super.getDefaultInstance();prepare(s);return s;}@Override public void inventoryTick(ItemStack s,Level l,Entity e,int slot,boolean selected){prepare(s);super.inventoryTick(s,l,e,slot,selected);}private static void prepare(ItemStack s){s.getOrCreateTag().putBoolean("Unbreakable",true);s.getOrCreateTag().putInt("HideFlags",4);if(s.getEnchantmentLevel(Enchantments.ALL_DAMAGE_PROTECTION)<4)s.enchant(Enchantments.ALL_DAMAGE_PROTECTION,4);if(s.getEnchantmentLevel(Enchantments.PROJECTILE_PROTECTION)<2)s.enchant(Enchantments.PROJECTILE_PROTECTION,2);if(s.getEnchantmentLevel(Enchantments.BLAST_PROTECTION)<2)s.enchant(Enchantments.BLAST_PROTECTION,2);}
 @Override public void appendHoverText(ItemStack s,Level l,List<Component>t,TooltipFlag f){t.add(Component.empty());for(int i=1;i<=6;i++)t.add(Component.translatable("item.finalparadox.void_armor.lore."+i));t.add(Component.empty());t.add(Component.translatable("item.finalparadox.legendary"));}
}
