package io.github.finalparadox.entity;
import io.github.finalparadox.ability.GlaivorusAbilityState;import io.github.finalparadox.registry.ModEntities;import net.minecraft.core.particles.*;import net.minecraft.nbt.CompoundTag;import net.minecraft.network.protocol.Packet;import net.minecraft.network.protocol.game.ClientGamePacketListener;import net.minecraft.server.level.*;import net.minecraft.sounds.*;import net.minecraft.world.effect.*;import net.minecraft.world.entity.*;import net.minecraft.world.level.Level;import net.minecraft.world.phys.Vec3;import net.minecraftforge.network.NetworkHooks;import org.joml.Vector3f;import java.util.UUID;
public final class PumpkinBombEntity extends Entity{
 private UUID ownerId;public PumpkinBombEntity(EntityType<PumpkinBombEntity>type,Level level){super(type,level);noCulling=true;}
 public static void spawn(ServerPlayer owner,Vec3 origin,double speed){PumpkinBombEntity b=new PumpkinBombEntity(ModEntities.PUMPKIN_BOMB.get(),owner.serverLevel());b.ownerId=owner.getUUID();b.setPos(origin.x,origin.y+.5,origin.z);double a=owner.getRandom().nextDouble()*Math.PI*2;b.setDeltaMovement(Math.cos(a)*speed,.4,Math.sin(a)*speed);owner.serverLevel().addFreshEntity(b);}
 @Override protected void defineSynchedData(){}@Override public void tick(){super.tick();if(level().isClientSide)return;Vec3 v=getDeltaMovement().add(0,-.04,0);move(MoverType.SELF,v);if(onGround())v=new Vec3(v.x*.65,0,v.z*.65);setDeltaMovement(v);if(level() instanceof ServerLevel s)s.sendParticles(new DustParticleOptions(new Vector3f(.392F,.769F,.216F),.8F),getX(),getY()+.3,getZ(),1,0,0,0,0);if(tickCount>=60)explode();}
 private void explode(){if(!(level() instanceof ServerLevel level)){discard();return;}ServerPlayer owner=ownerId==null?null:level.getServer().getPlayerList().getPlayer(ownerId);level.sendParticles(ParticleTypes.EXPLOSION,getX(),getY(),getZ(),1,0,0,0,0);level.sendParticles(new ItemParticleOption(ParticleTypes.ITEM,new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.PUMPKIN)),getX(),getY(),getZ(),50,0,0,0,.3);level.sendParticles(ParticleTypes.TOTEM_OF_UNDYING,getX(),getY(),getZ(),15,0,0,0,.4);level.playSound(null,blockPosition(),SoundEvents.FIREWORK_ROCKET_BLAST,SoundSource.PLAYERS,.5F,1.8F);if(owner!=null)for(LivingEntity e:level.getEntitiesOfClass(LivingEntity.class,getBoundingBox().inflate(3.2),x->GlaivorusAbilityState.isHostileTarget(owner,x))){e.hurt(owner.damageSources().playerAttack(owner),9);e.addEffect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN,40,2),owner);}for(ServerPlayer ally:level.players())if(ally.distanceToSqr(this)<=10.24){ally.addEffect(new MobEffectInstance(MobEffects.REGENERATION,120,1));ally.addEffect(new MobEffectInstance(MobEffects.DAMAGE_BOOST,120,1));}discard();}
 @Override protected void readAdditionalSaveData(CompoundTag t){if(t.hasUUID("Owner"))ownerId=t.getUUID("Owner");}@Override protected void addAdditionalSaveData(CompoundTag t){if(ownerId!=null)t.putUUID("Owner",ownerId);}@Override public Packet<ClientGamePacketListener>getAddEntityPacket(){return NetworkHooks.getEntitySpawningPacket(this);}
}
