package io.github.finalparadox.ability;

import io.github.finalparadox.entity.ArcaneTechniqueEntity;
import io.github.finalparadox.registry.ModItems;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.Mth;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.LivingEntity;

public final class ArcaneMasteryState {
    public static final String ABILITY_DAMAGE_KEY="finalparadox.arcane_ability_damage";
    private static final String ACTIVE="finalparadox.arcane_mastery_active",TIME="finalparadox.arcane_mastery_time",COOLDOWN="finalparadox.arcane_mastery_cooldown",PHASE="finalparadox.arcane_mastery_phase",SPIN_MASK="finalparadox.arcane_mastery_spin_mask",SPIN_WINDOW="finalparadox.arcane_mastery_spin_window",SPINNING="finalparadox.arcane_mastery_spinning",END_DELAY="finalparadox.arcane_mastery_end_delay";
    private ArcaneMasteryState(){}
    public static boolean isActive(ServerPlayer player){return player.getPersistentData().getBoolean(ACTIVE);}
    public static void start(ServerPlayer player){if(player.getPersistentData().getInt(COOLDOWN)>0){player.displayClientMessage(Component.translatable("message.finalparadox.arcane_mastery.cooldown"),true);return;}player.getPersistentData().putBoolean(ACTIVE,true);player.getPersistentData().putInt(TIME,500);player.getPersistentData().putInt(COOLDOWN,1080);player.getPersistentData().putInt(PHASE,0);player.getPersistentData().putBoolean(SPINNING,false);player.serverLevel().sendParticles(ParticleTypes.END_ROD,player.getX(),player.getY()+1,player.getZ(),40,.8,.8,.8,.3);player.level().playSound(null,player.blockPosition(),SoundEvents.EVOKER_CAST_SPELL,SoundSource.PLAYERS,1,1.3F);player.displayClientMessage(Component.translatable("message.finalparadox.arcane_mastery.started"),true);}
    public static void onTossDuringMastery(ServerPlayer player){int phase=player.getPersistentData().getInt(PHASE);if(phase==1){ArcaneTechniqueEntity.spawn(player,1);advance(player,2);}else if(phase==3){ArcaneTechniqueEntity.spawn(player,2);advance(player,4);}else if(phase==5){ArcaneTechniqueEntity.spawn(player,3);advance(player,6);player.getPersistentData().putInt(END_DELAY,20);}}
    public static void onJump(ServerPlayer player){if(isActive(player)&&player.getPersistentData().getInt(PHASE)==2){player.getPersistentData().putBoolean(SPINNING,true);player.getPersistentData().putInt(SPIN_WINDOW,80);player.getPersistentData().putInt(SPIN_MASK,0);}}
    public static void recordAttack(ServerPlayer player,LivingEntity target){if(!isActive(player)||player.getPersistentData().getBoolean(ABILITY_DAMAGE_KEY)||!player.getMainHandItem().is(ModItems.ARCANE_MASTER_BLADE.get())||!GlaivorusAbilityState.isHostileTarget(player,target))return;int phase=player.getPersistentData().getInt(PHASE);if(phase==0&&!player.onGround()){advance(player,1);return;}if(phase==4&&!player.onGround())advance(player,5);}
    private static void advance(ServerPlayer player,int next){player.getPersistentData().putInt(PHASE,next);player.getPersistentData().putBoolean(SPINNING,false);player.getPersistentData().remove(SPIN_MASK);player.getPersistentData().remove(SPIN_WINDOW);player.addEffect(new MobEffectInstance(MobEffects.MOVEMENT_SPEED,60,1));player.addEffect(new MobEffectInstance(MobEffects.DIG_SPEED,60,1));player.addEffect(new MobEffectInstance(MobEffects.REGENERATION,60,1));player.serverLevel().sendParticles(ParticleTypes.END_ROD,player.getX(),player.getY()+1,player.getZ(),6,0,0,0,.2);player.level().playSound(null,player.blockPosition(),SoundEvents.END_PORTAL_FRAME_FILL,SoundSource.PLAYERS,1,.7F);}
    public static void tick(ServerPlayer player){int cooldown=player.getPersistentData().getInt(COOLDOWN);if(cooldown>0){cooldown--;if(cooldown==0){player.getPersistentData().remove(COOLDOWN);player.displayClientMessage(Component.translatable("message.finalparadox.arcane_mastery.ready"),true);player.level().playSound(null,player.blockPosition(),SoundEvents.UI_BUTTON_CLICK.value(),SoundSource.PLAYERS,1,1.5F);}else player.getPersistentData().putInt(COOLDOWN,cooldown);}if(!isActive(player))return;int delay=player.getPersistentData().getInt(END_DELAY);if(delay>0){if(--delay<=0)end(player);else player.getPersistentData().putInt(END_DELAY,delay);return;}int time=player.getPersistentData().getInt(TIME)-1;if(time<=0){end(player);return;}player.getPersistentData().putInt(TIME,time);if(player.getPersistentData().getBoolean(SPINNING)){int window=player.getPersistentData().getInt(SPIN_WINDOW)-1;if(window<=0){player.getPersistentData().putBoolean(SPINNING,false);player.getPersistentData().remove(SPIN_MASK);player.getPersistentData().remove(SPIN_WINDOW);}else{player.getPersistentData().putInt(SPIN_WINDOW,window);float yaw=Mth.positiveModulo(player.getYRot()+45,360);int zone=((int)(yaw/90))&3;int mask=player.getPersistentData().getInt(SPIN_MASK)|(1<<zone);player.getPersistentData().putInt(SPIN_MASK,mask);if(Integer.bitCount(mask)>=3)advance(player,3);}}int phase=player.getPersistentData().getInt(PHASE);if(player.getMainHandItem().is(ModItems.ARCANE_MASTER_BLADE.get()))player.displayClientMessage(Component.translatable("message.finalparadox.arcane_mastery.phase."+phase,(time+9)/10),true);player.serverLevel().sendParticles(ParticleTypes.FIREWORK,player.getX(),player.getY()+1,player.getZ(),2,.3,.6,.3,0);}
    private static void end(ServerPlayer player){player.getPersistentData().remove(ACTIVE);player.getPersistentData().remove(TIME);player.getPersistentData().remove(PHASE);player.getPersistentData().remove(SPIN_MASK);player.getPersistentData().remove(SPIN_WINDOW);player.getPersistentData().remove(SPINNING);player.getPersistentData().remove(END_DELAY);player.serverLevel().sendParticles(ParticleTypes.LARGE_SMOKE,player.getX(),player.getY()+1,player.getZ(),12,.6,.6,.6,0);player.level().playSound(null,player.blockPosition(),SoundEvents.FIRE_EXTINGUISH,SoundSource.PLAYERS,1,1.4F);player.displayClientMessage(Component.translatable("message.finalparadox.arcane_mastery.ended"),true);}
}
