package io.github.finalparadox.ability;

import io.github.finalparadox.entity.ProfaneTechniqueEntity;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.core.particles.DustParticleOptions;
import net.minecraft.network.chat.Component;
import net.minecraft.network.protocol.game.ClientboundSetSubtitleTextPacket;
import net.minecraft.network.protocol.game.ClientboundSetTitleTextPacket;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.Mth;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.LivingEntity;
import io.github.finalparadox.registry.ModItems;
import org.joml.Vector3f;

public final class ProfaneStanceState {
    public static final String ACTIVE="finalparadox.profane.active", TIME="finalparadox.profane.time", PHASE="finalparadox.profane.phase", COOLDOWN="finalparadox.profane.cooldown", ABILITY_DAMAGE="finalparadox.profane.ability_damage";
    private static final String SPINNING="finalparadox.profane.spinning",SPIN_MASK="finalparadox.profane.spin_mask",SPIN_WINDOW="finalparadox.profane.spin_window",END_DELAY="finalparadox.profane.end_delay";
    private ProfaneStanceState(){}
    public static boolean active(ServerPlayer player){return player.getPersistentData().getBoolean(ACTIVE);}
    public static void onToss(ServerPlayer player){
        if(!active(player)){if(player.getPersistentData().getInt(COOLDOWN)>0){player.displayClientMessage(Component.translatable("message.finalparadox.profane.cooldown"),true);return;}start(player);return;}
        int phase=player.getPersistentData().getInt(PHASE);if(phase==1){ProfaneTechniqueEntity.spawn(player,ProfaneTechniqueEntity.ARS_GRAVITUM);advance(player,2);}else if(phase==3){ProfaneTechniqueEntity.spawn(player,ProfaneTechniqueEntity.PROFANE_SLASH);advance(player,4);}else if(phase==5){ProfaneTechniqueEntity.spawn(player,ProfaneTechniqueEntity.DARK_CHARGE);advance(player,6);player.getPersistentData().putInt(TIME,60);player.getPersistentData().putInt(END_DELAY,20);}
    }
    private static void start(ServerPlayer player){player.getPersistentData().putBoolean(ACTIVE,true);player.getPersistentData().putInt(TIME,800);player.getPersistentData().putInt(PHASE,0);player.getPersistentData().putInt(COOLDOWN,800);player.getPersistentData().remove(END_DELAY);showSubtitle(player,"message.finalparadox.profane.started");player.serverLevel().sendParticles(ParticleTypes.END_ROD,player.getX(),player.getY()+1,player.getZ(),20,0,0,0,.5);for(int i=0;i<24;i++){double a=i*Math.PI/12;player.serverLevel().sendParticles(ParticleTypes.END_ROD,player.getX()+Math.cos(a),player.getY()+1,player.getZ()+Math.sin(a),1,0,0,0,.4);}player.serverLevel().sendParticles(ParticleTypes.FLASH,player.getX(),player.getY()+1,player.getZ(),1,0,0,0,0);player.serverLevel().sendParticles(ParticleTypes.EXPLOSION,player.getX(),player.getY()+1,player.getZ(),1,0,0,0,0);player.level().playSound(null,player.blockPosition(),SoundEvents.EVOKER_CAST_SPELL,SoundSource.PLAYERS,1,1.3F);player.level().playSound(null,player.blockPosition(),SoundEvents.PLAYER_LEVELUP,SoundSource.PLAYERS,1,.9F);player.level().playSound(null,player.blockPosition(),SoundEvents.PLAYER_HURT_ON_FIRE,SoundSource.PLAYERS,.8F,1.2F);}
    public static void onJump(ServerPlayer player){if(active(player)&&player.getPersistentData().getInt(PHASE)==0){player.getPersistentData().putBoolean(SPINNING,true);player.getPersistentData().putInt(SPIN_WINDOW,80);player.getPersistentData().putInt(SPIN_MASK,0);}}
    public static void recordAttack(ServerPlayer player,LivingEntity target){if(!active(player)||player.getPersistentData().getBoolean(ABILITY_DAMAGE)||!player.getMainHandItem().is(ModItems.PROFANE_ARCANE_BLADE.get())||!GlaivorusAbilityState.isHostileTarget(player,target))return;int phase=player.getPersistentData().getInt(PHASE);if(phase==0&&player.getPersistentData().getBoolean(SPINNING)&&Integer.bitCount(player.getPersistentData().getInt(SPIN_MASK))>=3)advance(player,1);else if((phase==2||phase==4)&&!player.onGround())advance(player,phase+1);}
    private static void advance(ServerPlayer player,int next){player.getPersistentData().putInt(PHASE,next);player.getPersistentData().remove(SPINNING);player.getPersistentData().remove(SPIN_MASK);player.getPersistentData().remove(SPIN_WINDOW);player.addEffect(new MobEffectInstance(MobEffects.MOVEMENT_SPEED,60,1));player.addEffect(new MobEffectInstance(MobEffects.DIG_SPEED,60,1));player.addEffect(new MobEffectInstance(MobEffects.REGENERATION,60,1));player.serverLevel().sendParticles(ParticleTypes.END_ROD,player.getX(),player.getY()+1,player.getZ(),6,0,0,0,.2);player.level().playSound(null,player.blockPosition(),SoundEvents.END_PORTAL_FRAME_FILL,SoundSource.PLAYERS,1,.7F);player.level().playSound(null,player.blockPosition(),SoundEvents.EXPERIENCE_ORB_PICKUP,SoundSource.PLAYERS,1,.7F);}
    public static void tick(ServerPlayer player){int cd=player.getPersistentData().getInt(COOLDOWN);if(cd>0){if(--cd==0){player.getPersistentData().remove(COOLDOWN);player.displayClientMessage(Component.translatable("message.finalparadox.profane.ready"),true);player.level().playSound(null,player.blockPosition(),SoundEvents.UI_BUTTON_CLICK.value(),SoundSource.PLAYERS,1,1.5F);}else player.getPersistentData().putInt(COOLDOWN,cd);}if(!active(player))return;spawnAura(player);int delay=player.getPersistentData().getInt(END_DELAY);if(delay>0){if(--delay<=0)end(player);else player.getPersistentData().putInt(END_DELAY,delay);return;}int time=player.getPersistentData().getInt(TIME)-1;if(time<=0){end(player);return;}player.getPersistentData().putInt(TIME,time);if(player.getPersistentData().getBoolean(SPINNING)){int window=player.getPersistentData().getInt(SPIN_WINDOW)-1;if(window<=0){player.getPersistentData().remove(SPINNING);player.getPersistentData().remove(SPIN_MASK);player.getPersistentData().remove(SPIN_WINDOW);}else{player.getPersistentData().putInt(SPIN_WINDOW,window);int yaw=Math.abs(Mth.floor(player.getYRot()));int mask=player.getPersistentData().getInt(SPIN_MASK);if(yaw<=110||yaw>=340)mask|=1;if(yaw>=71&&yaw<=200)mask|=2;if(yaw>=161&&yaw<=290)mask|=4;if(yaw<=20||yaw>=251)mask|=8;player.getPersistentData().putInt(SPIN_MASK,mask);}}int phase=player.getPersistentData().getInt(PHASE);if(phase<=5&&player.getMainHandItem().is(ModItems.PROFANE_ARCANE_BLADE.get()))player.displayClientMessage(Component.translatable("message.finalparadox.profane.phase."+phase,(time+19)/20),true);}
    private static void spawnAura(ServerPlayer player){if(player.tickCount%10==0)player.serverLevel().sendParticles(new DustParticleOptions(new Vector3f(.184F,0F,.478F),1F),player.getX(),player.getY()+1,player.getZ(),4,.3,.6,.3,0);}
    private static void end(ServerPlayer player){player.getPersistentData().remove(ACTIVE);player.getPersistentData().remove(TIME);player.getPersistentData().remove(PHASE);player.getPersistentData().remove(SPINNING);player.getPersistentData().remove(SPIN_MASK);player.getPersistentData().remove(SPIN_WINDOW);player.getPersistentData().remove(END_DELAY);player.serverLevel().sendParticles(ParticleTypes.LARGE_SMOKE,player.getX(),player.getY()+1,player.getZ(),12,.6,.6,.6,0);player.level().playSound(null,player.blockPosition(),SoundEvents.FIRE_EXTINGUISH,SoundSource.PLAYERS,1,1.4F);showSubtitle(player,"message.finalparadox.profane.ended");}
    private static void showSubtitle(ServerPlayer player,String key){player.connection.send(new ClientboundSetTitleTextPacket(Component.empty()));player.connection.send(new ClientboundSetSubtitleTextPacket(Component.translatable(key)));}
}
